spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: bcd127
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: f3e1fb52-0511-4055-9014-55c73eb7184c
  expiration: 999999