spring:
  jpa:
    hibernate:
      ddl-ayto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: bcd127
  jackson:
    default-property-inclusion: non_null